### ISSUE TITLE
SSD1327 lacking grayscale support

### ISSUE THREAD

**Issue by markbirss** [adafruit/Adafruit_Blinka_Displayio#105]
Connecting the same SSD1327 display using same library same example

Example:
https://github.com/adafruit/Adafruit_CircuitPython_SSD1327/blob/main/examples/ssd1327_simpletest.py

Guide:
https://learn.adafruit.com/adafruit-grayscale-1-5-128x128-oled-display/circuitpython-wiring-and-usage

CircuitPython on ESP32
![image](https://user-images.githubusercontent.com/22388007/221535787-a57f5ea2-de5d-4d11-8ad2-5fcb204d589b.png)

BLINKA MCP2221A
![image](https://user-images.githubusercontent.com/22388007/221535595-c48225ae-3ec3-4d60-8fb6-aa4263fe0d11.png)

**Comment by makermelissa** [comment]
I think this is related to the Adafruit_Blinka_Displayio library rather than the driver since it works in CircuitPython. I'm almost certain it's related to https://github.com/adafruit/Adafruit_Blinka_Displayio/issues/72.

Could you provide some more details such as if you have it wired up with I2C or SPI? Thanks.

**Comment by makermelissa** [comment]
Also, since this display is known to have problems on Blinka, that's why we haven't made a Python Usage section to the guide yet.

**Comment by markbirss** [comment]
The pictured display was connected via I2C.

**Comment by makermelissa** [comment]
Thanks

**Comment by markbirss** [comment]
It is also not working  correctly onnected to PICO BLINKA U2IF

**Comment by makermelissa** [comment]
Yeah, it's probably the same library issue.

**Comment by makermelissa** [comment]
I've been taking a closer look and the format of the I2C data actually looks closer than I expected. I believe the issue is actually the grayscale support of this display.

**Comment by makermelissa** [comment]
Still digging in, but at this point, I think one of the main issues is that each pixel color should only be a single byte and it's using 2 bytes for the color.
