### ISSUE TITLE
Finish ColorConverter

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_Blinka_Displayio#7]
ColorConverter is partially implemented and will be a big part of ePaper Displays. See #3. This likely could be reworked to make use of Pillow for dithering.

**Comment by makermelissa** [comment]
This is partially done in #20, but needs dithering added when ePaper Display support is added.

**Comment by wolfmanjm** [comment]
Please note that single pixel/monchrome displays are also not currently supported. (I found out when I tried to get SSD1306 to work :)
