### ISSUE TITLE
Update type annotations to use circuitpython_typing

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_Blinka_Displayio#82]
I know typing is still a little in flux, but should uses of the contained `_typing` types be switched to `circuitpython_typing`?

**Comment by dhalbert** [comment]
Yes, definitely, assuming it is possible here.

**Comment by tekktrik** [comment]
Sounds good!  I'll get on this soon!

**Comment by makermelissa** [comment]
Yeah, I created `_typing` before `circuitpython_typing` existed.
