### ISSUE TITLE
SSD1306 displays not working properly

### ISSUE THREAD

**Issue by HenryHu** [adafruit/Adafruit_Blinka_Displayio#95]
I have a 128x64 display using SSD1306, and it's not working properly.
I noticed that 16384 bytes of data is sent every time, while only 1024 bytes (128 x 64 / 8, 1 bit per pixel) should be sent.
I've read some other issues and I understand that this is a known issue. Creating this issue to help others find it.
Can we add some text to the README file to notify future users that monochrome displays are not supported properly yet?

**Comment by credwards-dynovas** [comment]
I also have a monochrome SSD1306 128x64 display and it is also not working properly.
In particular, the issue I'm having is that pixels are not displaying as expected. This could be that the extra bytes sent are being misinterpreted - example below:
```
color_bitmap = displayio.Bitmap(WIDTH, HEIGHT, 2)
color_bitmap[1,1]=1
color_palette = displayio.Palette(2)
color_palette[0] = 0x000000
color_palette[1] = 0xFFFFFF
bg_sprite = displayio.TileGrid(color_bitmap, pixel_shader=color_palette, x=0, y=0)
splash.append(bg_sprite)
```
Results in more than 1 pixel turning white. The index of the pixel is also incorrect (see attached photo)
![20220727_155636960_iOS](https://user-images.githubusercontent.com/100386642/181294264-7e3fd7b7-1f14-4ce0-8465-f82231d6af51.jpg)

Potentially related: calling ```sleep()``` on the display results in the following error:
```
Traceback (most recent call last):
  File "/home/dynovas/oled_test/oled_test.py", line 68, in <module>
    try: main()
  File "/home/dynovas/oled_test/oled_test.py", line 11, in main
    circuitpython()
  File "/home/dynovas/oled_test/oled_test.py", line 63, in circuitpython
    oled_display.sleep()
  File "/usr/local/lib/python3.9/dist-packages/adafruit_displayio_ssd1306.py", line 108, in sleep
    self.bus.send(0xAE, b"")  # 0xAE = display off, sleep mode
  File "/usr/local/lib/python3.9/dist-packages/displayio/_i2cdisplay.py", line 86, in send
    self._send(DISPLAY_COMMAND, CHIP_SELECT_UNTOUCHED, bytes([command] + data))
TypeError: can only concatenate list (not "bytes") to list
```
It seems like there may be an issue with how the ```I2CDisplay``` class sends its data

**Comment by omerk** [comment]
I think I've just been bitten by this as well, can't get the I2C 128x64 SSD1306 display I have in front of me working on Linux. There appears to be too many writes (screen flickers with seemingly random pixels being lit up), which probably confirms the diagnosis in the first port that there's just too much data being sent to the controller.

If these displays are not indeed supported (deliberate design choice or not) then a note/disclaimer in the README could save serious time/sanity.

Thanks.
